import type { TutorWithProfile, TutorApplication, User } from "./types"

export const MOCK_TUTORS: TutorWithProfile[] = [
  {
    id: "a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d",
    email: "sarah.hassan@aub.edu.lb",
    fullName: "Sarah Hassan",
    role: "tutor",
    avatarUrl: "/professional-woman-student.jpg",
    profile: {
      id: "prof-1",
      userId: "a1b2c3d4-e5f6-4a5b-8c9d-0e1f2a3b4c5d",
      bio: "Senior Computer Science student with 2 years of tutoring experience. Passionate about helping students understand complex algorithms and data structures. I believe in making programming fun and accessible to everyone!",
      subjects: ["Computer Science", "Programming", "Algorithms", "Data Structures"],
      hourlyRate: 15.0,
      availability: {},
      totalSessions: 45,
      averageRating: 4.8,
      isVerified: true,
    },
  },
  {
    id: "b2c3d4e5-f6a7-5b6c-9d0e-1f2a3b4c5d6e",
    email: "karim.nader@aub.edu.lb",
    fullName: "Karim Nader",
    role: "tutor",
    avatarUrl: "/professional-man-student.jpg",
    profile: {
      id: "prof-2",
      userId: "b2c3d4e5-f6a7-5b6c-9d0e-1f2a3b4c5d6e",
      bio: "Mathematics major specializing in Calculus and Linear Algebra. I make math fun and easy to understand! My teaching style focuses on building intuition before diving into formulas.",
      subjects: ["Mathematics", "Calculus", "Linear Algebra", "Statistics"],
      hourlyRate: 12.0,
      availability: {},
      totalSessions: 62,
      averageRating: 4.9,
      isVerified: true,
    },
  },
  {
    id: "c3d4e5f6-a7b8-6c7d-0e1f-2a3b4c5d6e7f",
    email: "lina.khoury@aub.edu.lb",
    fullName: "Lina Khoury",
    role: "tutor",
    avatarUrl: "/professional-woman-scientist.png",
    profile: {
      id: "prof-3",
      userId: "c3d4e5f6-a7b8-6c7d-0e1f-2a3b4c5d6e7f",
      bio: "Biology student with a focus on molecular biology and genetics. Available for both theory and lab help. I love breaking down complex biological concepts into simple, memorable explanations.",
      subjects: ["Biology", "Chemistry", "Genetics", "Biochemistry"],
      hourlyRate: 13.0,
      availability: {},
      totalSessions: 38,
      averageRating: 4.7,
      isVerified: true,
    },
  },
  {
    id: "d4e5f6a7-b8c9-7d8e-1f2a-3b4c5d6e7f8a",
    email: "omar.said@aub.edu.lb",
    fullName: "Omar Said",
    role: "tutor",
    avatarUrl: "/professional-man-business.png",
    profile: {
      id: "prof-4",
      userId: "d4e5f6a7-b8c9-7d8e-1f2a-3b4c5d6e7f8a",
      bio: "Economics and Business student. Can help with micro/macro economics, statistics, and business courses. I use real-world examples to make economic concepts come alive.",
      subjects: ["Economics", "Statistics", "Business", "Finance"],
      hourlyRate: 14.0,
      availability: {},
      totalSessions: 29,
      averageRating: 4.6,
      isVerified: true,
    },
  },
  {
    id: "e5f6a7b8-c9d0-8e9f-2a3b-4c5d6e7f8a9b",
    email: "maya.el-khoury@aub.edu.lb",
    fullName: "Maya El-Khoury",
    role: "tutor",
    avatarUrl: "/professional-woman-writer.png",
    profile: {
      id: "prof-5",
      userId: "e5f6a7b8-c9d0-8e9f-2a3b-4c5d6e7f8a9b",
      bio: "English Literature major with experience in academic writing and essay composition. Native English speaker. I help students develop their writing voice and critical thinking skills.",
      subjects: ["English", "Writing", "Literature", "Academic Writing"],
      hourlyRate: 11.0,
      availability: {},
      totalSessions: 51,
      averageRating: 5.0,
      isVerified: true,
    },
  },
  {
    id: "f6a7b8c9-d0e1-9f0a-3b4c-5d6e7f8a9b0c",
    email: "rami.haddad@aub.edu.lb",
    fullName: "Rami Haddad",
    role: "tutor",
    avatarUrl: "/professional-engineer.png",
    profile: {
      id: "prof-6",
      userId: "f6a7b8c9-d0e1-9f0a-3b4c-5d6e7f8a9b0c",
      bio: "Physics student passionate about mechanics, electromagnetism, and quantum physics. Patient and thorough. I believe physics is about understanding the universe, not just memorizing equations.",
      subjects: ["Physics", "Mathematics", "Engineering", "Mechanics"],
      hourlyRate: 13.5,
      availability: {},
      totalSessions: 34,
      averageRating: 4.8,
      isVerified: true,
    },
  },
]

export const MOCK_APPLICATIONS: TutorApplication[] = [
  {
    id: "app-1",
    userId: "pending-user-1",
    fullName: "Ahmad Khalil",
    email: "ahmad.khalil@aub.edu.lb",
    bio: "Third-year Engineering student specializing in Mechanical Engineering. I have strong fundamentals in physics and mathematics.",
    subjects: ["Physics", "Mathematics", "Engineering"],
    hourlyRate: 12.0,
    status: "pending",
    submittedAt: new Date("2024-01-15"),
  },
  {
    id: "app-2",
    userId: "pending-user-2",
    fullName: "Nour Mansour",
    email: "nour.mansour@aub.edu.lb",
    bio: "Psychology major with experience in research methods and statistics. Passionate about helping students understand behavioral science.",
    subjects: ["Psychology", "Statistics", "Research Methods"],
    hourlyRate: 11.0,
    status: "pending",
    submittedAt: new Date("2024-01-18"),
  },
]

export const ALL_SUBJECTS = [
  "Computer Science",
  "Programming",
  "Algorithms",
  "Data Structures",
  "Mathematics",
  "Calculus",
  "Linear Algebra",
  "Statistics",
  "Biology",
  "Chemistry",
  "Genetics",
  "Biochemistry",
  "Economics",
  "Business",
  "Finance",
  "English",
  "Writing",
  "Literature",
  "Academic Writing",
  "Physics",
  "Engineering",
  "Mechanics",
  "Psychology",
  "Research Methods",
]

export const MOCK_ADMIN_USER: User = {
  id: "admin-1",
  email: "admin@levelup.aub.edu.lb",
  fullName: "Admin User",
  role: "admin",
}
